
engine: mysql

host: localhost
user: jseeder
password: jseeder
database: fabric
port: 3306

includeTables:
    master_cities:
        seedSize: 100
        # Other configs per table may follow..
        # Also column specific config can also follow in same pattern..
    master_countries:
        seedSize: 100
    master_states:
        seedSize: 100
